name: ECG

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  CI:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Generate data files
      run : |
        python dataset-generation-pool.py
      working-directory:
        ./scripts

    - name: Generate annotation files
      run: |
        python annotation-generation.py
      working-directory:
        ./scripts